version: '3.7'
services:
  # mysql:
  #   image: mysql:8.0.33-debian
  #   environment:
  #     MYSQL_ROOT_PASSWORD: toor
  #     MYSQL_DATABASE: app
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: toor
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./html:/usr/share/nginx/html
    # depends_on:
    #   - mysql
